import { GameEventSchema, type GameEvent } from "~/game/protocol/messages";

export const DEMO_EVENTS: GameEvent[] = GameEventSchema.array().parse([
  {
    type: "match_start",
    seats: [
      { seat: 0, userId: "demo-east", displayName: "Kandora" },
      { seat: 1, userId: "demo-south", displayName: "Mika" },
      { seat: 2, userId: "demo-west", displayName: "Ren" },
      { seat: 3, userId: "demo-north", displayName: "Aoi" },
    ],
    ruleSet: "tenhou-default",
  },
  {
    type: "hand_start",
    round: 0,
    dealer: 0,
    roundWind: "E",
    roundNumber: 1,
    honba: 0,
    riichiSticks: 0,
    scores: [25_000, 25_000, 25_000, 25_000],
    startingHands: [
      [
        "1m",
        "2m",
        "3m",
        "4m",
        "5m",
        "6m",
        "7p",
        "8p",
        "9p",
        "2s",
        "3s",
        "4s",
        "5z",
      ],
      [
        "2m",
        "3m",
        "4m",
        "3p",
        "4p",
        "5p",
        "6p",
        "7p",
        "8p",
        "6s",
        "7s",
        "8s",
        "1z",
      ],
      [
        "5m",
        "6m",
        "7m",
        "1p",
        "2p",
        "3p",
        "4p",
        "5p",
        "6p",
        "7s",
        "8s",
        "9s",
        "2z",
      ],
      [
        "7m",
        "8m",
        "9m",
        "2p",
        "3p",
        "4p",
        "1s",
        "2s",
        "3s",
        "4s",
        "5s",
        "6s",
        "3z",
      ],
    ],
    doraIndicators: ["4z"],
    dice: [3, 5],
  },
  { type: "draw", seat: 0, tile: "5z", wallRemaining: 69 },
  {
    type: "discard",
    seat: 0,
    tile: "7p",
    tsumogiri: false,
    discardSource: "hand",
  },
  { type: "draw", seat: 1, tile: "9s", wallRemaining: 68 },
  {
    type: "discard",
    seat: 1,
    tile: "1z",
    tsumogiri: false,
    discardSource: "hand",
  },
  { type: "draw", seat: 2, tile: "7z", wallRemaining: 67 },
  {
    type: "discard",
    seat: 2,
    tile: "2z",
    tsumogiri: false,
    discardSource: "hand",
  },
  { type: "draw", seat: 3, tile: "1p", wallRemaining: 66 },
  {
    type: "discard",
    seat: 3,
    tile: "3z",
    tsumogiri: false,
    discardSource: "hand",
  },
  { type: "draw", seat: 0, tile: "6z", wallRemaining: 65 },
]);

export const DEMO_SEAT_NAMES: [string, string, string, string] = [
  "Kandora",
  "Mika",
  "Ren",
  "Aoi",
];